from ctypes import *
from enum import Enum

class CTRL_TYPE(Enum):
  VIRTIO_GPU_UNDEFINED = 0
  GET_DISPLAY_INFO = 0x100
  RESOURCE_CREATE_2D = 0x101
  RESOURCE_UNREF = 0x102
  SET_SCANOUT = 0x103
  RESOURCE_FLUSH = 0x104
  TRANSFER_TO_HOST_2D = 0x105
  RESOURCE_ATTACH_BACKING = 0x106
  RESOURCE_DETACH_BACKING = 0x107
  GET_CAPSET_INFO = 0x108
  GET_CAPSET = 0x109
  CTX_CREATE = 0x200
  CTX_DESTROY = 0x201
  CTX_ATTACH_RESOURCE = 0x202
  CTX_DETACH_RESOURCE = 0x203
  RESOURCE_CREATE_3D = 0x204
  TRANSFER_TO_HOST_3D = 0x205
  TRANSFER_FROM_HOST_3D = 0x206
  SUBMIT_3D = 0x207
  UPDATE_CURSOR = 0x300
  MOVE_CURSOR = 0x301
  RESP_OK_NODATA = 0x1100
  RESP_OK_DISPLAY_INFO = 0x1101
  RESP_OK_CAPSET_INFO = 0x1102
  RESP_OK_CAPSET = 0x1103
  RESP_ERR_UNSPEC = 0x1200
  RESP_ERR_OUT_OF_MEMORY = 0x1201
  RESP_ERR_INVALID_SCANOUT_ID = 0x1202
  RESP_ERR_INVALID_RESOURCE_ID = 0x1203
  RESP_ERR_INVALID_CONTEXT_ID = 0x1204
  RESP_ERR_INVALID_PARAMETER = 0x1205
  API_FORWARDING = 0x1206
  SHOW_DEBUG = 0x1207

class CMD_3D(Enum):
  NOP = 0
  CREATE_OBJECT = 1
  BIND_OBJECT = 2
  DESTROY_OBJECT = 3
  SET_VIEWPORT_STATE = 4
  SET_FRAMEBUFFER_STATE = 5
  SET_VERTEX_BUFFERS = 6
  CLEAR = 7
  DRAW_VBO = 8
  RESOURCE_INLINE_WRITE = 9
  SET_SAMPLER_VIEWS = 10
  SET_INDEX_BUFFER = 11
  SET_CONSTANT_BUFFER = 12
  SET_STENCIL_REF = 13
  SET_BLEND_COLOR = 14
  SET_SCISSOR_STATE = 15
  BLIT = 16
  RESOURCE_COPY_REGION = 17
  BIND_SAMPLER_STATES = 18
  BEGIN_QUERY = 19
  END_QUERY = 20
  GET_QUERY_RESULT = 21
  SET_POLYGON_STIPPLE = 22
  SET_CLIP_STATE = 23
  SET_SAMPLE_MASK = 24
  SET_STREAMOUT_TARGETS = 25
  SET_RENDER_CONDITION = 26
  SET_UNIFORM_BUFFER = 27
  SET_SUB_CTX = 28
  CREATE_SUB_CTX = 29
  DESTROY_SUB_CTX = 30
  BIND_SHADER = 31

class VIRGL_OBJ(Enum):
  NULL = 0
  BLEND = 1
  RASTERIZER = 2
  DSA = 3
  SHADER = 4
  VERTEX_ELEMENTS = 5
  SAMPLER_VIEW = 6
  SAMPLER_STATE = 7
  SURFACE = 8
  QUERY = 9
  STREAMOUT_TARGET = 10
  MAX_OBJECTS = 11

class GPU_CTRL_HDR(Structure):
  _fields_ = [("type", c_ulong),
              ("flags", c_ulong),
              ("fence_id", c_ulonglong),
              ("ctx_id", c_ulong),
              ("padding", c_ulong)]

